name: Android CI

env:
  main_project_module: app

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

        - name: Create key.properties
          run: |
            echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
            echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
            echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "oracle"
          cache: "gradle"

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: "stable"
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK RELEASE
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) debug generated
          path: build/app/outputs/apk/release/app-release.apk
